Repository blackcowmoo/moomark-frontend, pull requests merged in 2021-12, with the labels that each got.

#9 Add build and push actions
  .dockerignore
  .github/workflows/develop-build.yaml
  .github/workflows/docker-build-and-push.yaml
  Dockerfile
Labels: deploy

#19 Refactor PostView, PostList
  public/logo.svg
  src/components/GlobalHeader/Logo.svg
  src/components/GlobalHeader/SearchForm/Search.svg
  src/components/GlobalHeader/ThemeToggle/Moon.svg
  src/components/GlobalHeader/ThemeToggle/Sun.svg
  src/components/GlobalHeader/ThemeToggle/ThemeToggle.module.scss
  src/components/GlobalHeader/ThemeToggle/index.tsx
  src/components/GlobalHeader/header.module.scss
  src/components/PostList/DefaultPostList/DefaultPostList.module.scss
  src/components/PostList/DefaultPostList/DefaultPostList.tsx
  src/components/PostList/DefaultPostList/DefaultViewItem.tsx
  src/components/PostList/TileViewPostList/TileViewItem.tsx
  src/components/PostList/TileViewPostList/TileViewPostList.module.scss
  src/components/PostViewer/PostViewer.module.scss
  src/components/PostViewer/index.tsx
  src/components/PostViewer/mockdata.ts
  src/components/layout/AppLayout.module.scss
  src/components/layout/AppLayout.tsx
  src/components/layout/HomeLayout/HomeLayout.module.scss
  src/components/layout/HomeLayout/index.tsx
  src/components/layout/MainLayout/index.tsx
  src/components/layout/MainLayout/main.module.scss
  src/pages/404/index.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/global.scss
  src/utils/mock/index.ts
Labels: enhancement, deploy, refactor, style

#20 Add image push trigger at pr on deploy label and image tag use pr sha
  .github/workflows/docker-build-and-push.yaml
Labels: deploy

#22 fix docker push
  .github/workflows/docker-build-and-push.yaml
Labels: deploy

#24 BasePath modified by env value
  .github/workflows/docker-build-and-push.yaml
  next.config.js
Labels: enhancement, deploy

#23 Refactor Post Page
  public/favicon.svg
  src/components/Comment/Comment.module.scss
  src/components/Comment/CommentContent/CommentContent.module.scss
  src/components/Comment/CommentContent/Content/Content.module.scss
  src/components/Comment/CommentContent/Content/Footer.tsx
  src/components/Comment/CommentContent/Content/Header.tsx
  src/components/Comment/CommentContent/Content/index.tsx
  src/components/Comment/CommentContent/Reply.tsx
  src/components/Comment/CommentContent/index.tsx
  src/components/Comment/CommentInputForm/CommentInputForm.module.scss
  src/components/Comment/CommentInputForm/index.tsx
  src/components/Comment/index.tsx
  src/components/CommentBox/Comment.tsx
  src/components/CommentBox/CommentInputForm.tsx
  src/components/CommentBox/Reply.tsx
  src/components/CommentBox/comment.module.scss
  src/components/CommentBox/index.tsx
  src/components/PostContents/MarkdownRender/markdown.module.scss
  src/components/PostHeader/postHeader.module.scss
  src/components/PostList/TileViewPostList/TileViewItem.tsx
  src/components/PostViewer/index.tsx
  src/components/PostViewer/mockdata.ts
  src/components/common/TagList/tag.module.scss
  src/pages/_document.tsx
  src/styles/global.scss
Labels: deploy, refactor, style
